### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by riesinger** [glidingthroughspace/paper-tracker#3]
## Nächstes Treffen
- [x] **Konkrete Anforderungen (idealerweise mit Gewichtung)**
	- Baugröße (P0)
	- Akkulaufzeit von mehreren Tagen (P1)
- [x] **Detailliertes Beispiel eines/mehrerer Prozesse**
	- _Wollte uns einen Bestellprozess senden, es gab allerdings noch keine Rückmeldung_
- [X] **Kostenübernahme Bestellungen / Bestellprozess**
	Aktuell bei Banggood bestellt. Kann man Rechnungen einreichen? Welches Budget haben wir? 
	- Ja, wir müssen eine Rechnung haben, die können wir einreichen (Bei unter 100€)
- [X] **WLAN-Zugang IoT-Geräte -> Sollen wir eduroam benutzen?**
	Ideal wäre etwas mit statischer IP-Adresse
	- Wir haben einen gesonderten Nutzer bekommen und sollen `DHBW-KA` nutzen. Hier sollte es kein P2P-Firewalling geben
- [X] **CAD-Software (für das Case)**
	- Silvan nutzt FreeCAD
- [X] **Abwägung Gewicht/Fläche/Tiefe/Akkulaufzeit**
	- Am wichtigsten ist die generelle Größe, Akkulaufzeit ist nicht so wichtig
- [X] **Custom PCB (China-Bestellung, wahrscheinlich JLCPCB)**
	- Siehe oben. Rechnung kann man einreichen
- [X] **Lötstation/Arbeitsplatz E-Technik**
	- Sollte im Raum gegenüber von Herrn Hüneborg (E314) stehen
- [X] **Mindestanforderung Akkulaufzeit**
	- "Einige Tage"

## Danach
- [x] **Grober Umriss des Datenmodells aus Anforderungen**
- [ ] **Vergleich der RSS der einzelnen Chips (ist diese allgemeingültig)**

## Sonstiges
- [x] **Genaue Spezifikation der API Backend <-> Tracker**
- [X] **Untersuchung Knopfzelle+Supercap / LiPo / Li-Ion**
	Eindeutig LiPo, da der TinyPICO das schon kann
